# Generated by Django 4.1.2 on 2024-07-05 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPro',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaAdmin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=100)),
                ('apellido_admin', models.CharField(max_length=100)),
                ('gmail_admin', models.EmailField(max_length=254, unique=True)),
                ('direccion_admin', models.CharField(max_length=255)),
                ('clave_admin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=100)),
                ('apellido_cli', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_cuenta', models.EmailField(max_length=254, unique=True)),
                ('clave_cuenta', models.CharField(max_length=255)),
                ('cuenta_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_cuenta', to='mascota.cuentacliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('descripcion_pro', models.TextField()),
                ('valor_pro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mascota.categoriapro')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaBoleta',
            fields=[
                ('id_vol_fact', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=100)),
                ('apellido_cli', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('gmail_cli', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='mascota.cuentacliente')),
                ('productos', models.ManyToManyField(related_name='facturas', to='mascota.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cuentacliente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='mascota.genero'),
        ),
    ]
