# Generated by Django 4.1.2 on 2024-07-05 15:16

from django.db import migrations, models
import mascota.models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=mascota.models.product_image_upload_path),
        ),
    ]
