# Generated by Django 4.1.2 on 2024-07-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='default_code', max_length=20, unique=True),
        ),
    ]
