# Generated by Django 4.1.2 on 2024-07-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_alter_producto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAdmin',
            fields=[
                ('id_registro_admin', models.AutoField(primary_key=True, serialize=False)),
                ('gmail_admin', models.EmailField(max_length=254, unique=True)),
                ('clave_admin', models.CharField(max_length=255)),
                ('cuenta_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_admin', to='mascota.cuentaadmin')),
            ],
        ),
    ]
